# Generated by Django 4.2 on 2023-06-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('participationcontest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contestsmodel')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
            },
        ),
    ]
