trigger:
  branches:
    include:
      - develop

variables:
  - group: Azure Info
  - group: Azure web app

pool:
  vmImage: $(AZ_VM_IMAGE_NAME)

steps:
  - task: NodeTool@0
    displayName: "Install Node"
    inputs:
      versionSource: "spec"
      versionSpec: $(NODE_VERSION)

  - script: |
      npm ci
    workingDirectory: "$(System.DefaultWorkingDirectory)/$(PROJECT_ROOT)"
    displayName: "Install dependencies"

  - script: |
      npm run lint:ci
    workingDirectory: "$(System.DefaultWorkingDirectory)/$(PROJECT_ROOT)"
    continueOnError: true
    displayName: "Lint"

  - script: |
      npm run test --if-present
    workingDirectory: "$(System.DefaultWorkingDirectory)/$(PROJECT_ROOT)"
    displayName: "Test"
