trigger: none

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '6c18588a-5e0d-46e5-bc25-cc2a5f2e84b0'

  # Web app name
  webAppName: 'spiri-move'

  # Environment name
  environmentName: 'spiri-move'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      displayName: 'Install Node'
      inputs:
        versionSource: 'spec'
        versionSpec: '18.x'
      
    - script: |
        npm ci
        npm run build
      workingDirectory: '$(build.sourcesdirectory)/webclient'
      displayName: 'Install dependencies and build app'

    - task: ArchiveFiles@2
      displayName: 'Package build'
      inputs:
        rootFolderOrFile: '$(build.sourcesdirectory)/webclient/dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: $(webAppName)'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              deployToSlotOrASE: true
              resourceGroupName: FrontEnd
              slotName: production
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'pm2 serve /home/site/wwwroot --spa --no-daemon'