trigger:
  branches:
    include:
      - develop

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      npm ci
      npm run build
    workingDirectory: "$(build.sourcesdirectory)/webclient"
    displayName: "npm install and build"
