version: '2.1'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    environment:
     - POSTGRES_DB_USER=spiri_move
     - POSTGRES_DB_PW=12345
     - POSTGRES_DB_NAME=spiri_move
    ports:
      - "8000:8000"
    volumes:
      - .:/spiri_move
    tty: true
    restart: always
    depends_on:
      - db
    command: sh -c "python manage.py runsslserver 0.0.0.0:8000"
  db:
   image: postgres:13-alpine
   environment:
     - POSTGRES_DB_USER=spiri_move
     - POSTGRES_DB_PW=12345
     - POSTGRES_DB_NAME=spiri_move
   volumes:
     - data:/var/lib/postgresql/data
   expose:
     - "5432"
   ports:
     - "5432:5432"
  redis:
    image: redis:alpine
volumes:
  data: