version: '2.1'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    environment:
     - POSTGRES_USER=spiri_move
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=spiri_move
    ports:
      - "8000:8000"
    volumes:
      - .:/spiri_move
    tty: true
    restart: always
    command: sh -c "./docker/wait-for.sh -c 'nc -z db 5432' -t 30 && python manage.py runserver 0.0.0.0:8000"
  db:
   image: postgres:13-alpine
   environment:
     - POSTGRES_USER=spiri_move
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=spiri_move
   volumes:
     - data:/var/lib/postgresql/data
   expose:
     - "5432"
   ports:
     - "5432:5432"
  redis:
    image: redis:alpine
volumes:
  data: