# Generated by Django 4.2 on 2023-06-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Phone'),
        ),
    ]
