# Generated by Django 4.2 on 2023-06-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_display_name_user_office_alter_user_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telephone',
            new_name='phone',
        ),
    ]
