# Generated by Django 4.2 on 2023-06-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_telephone_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deactive_date',
        ),
    ]
