# Generated by Django 4.2 on 2023-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['display_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MODERATOR', 'Moderator'), ('PARTICIPANT', 'Participant')], max_length=50, unique=True, verbose_name='Role'),
        ),
    ]
