# Generated by Django 4.2 on 2023-06-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0002_participationmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
