# Generated by Django 4.2 on 2023-06-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0004_participationmodel_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefisPopupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Defis Popup',
                'verbose_name_plural': 'Defis Popup',
            },
        ),
        migrations.CreateModel(
            name='UnApprovedParticipation',
            fields=[
            ],
            options={
                'verbose_name': 'Participation non approuvée',
                'verbose_name_plural': 'Participations non approuvées',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('participation.participationmodel',),
        ),
        migrations.AddField(
            model_name='participationmodel',
            name='defis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participation.defispopupmodel'),
        ),
    ]
