# Generated by Django 4.2 on 2023-06-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0005_defispopupmodel_unapprovedparticipation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participationmodel',
            old_name='participationcontest',
            new_name='contest',
        ),
    ]
