# Generated by Django 4.2 on 2023-06-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0006_rename_participationcontest_participationmodel_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participation type',
                'verbose_name_plural': 'Participations type',
            },
        ),
        migrations.RemoveField(
            model_name='participationmodel',
            name='defis',
        ),
        migrations.AddField(
            model_name='participationmodel',
            name='is_in_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participationmodel',
            name='is_intensive',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DefisPopupModel',
        ),
        migrations.AddField(
            model_name='participationmodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participation.participationtypemodel'),
        ),
    ]
