# Generated by Django 4.2 on 2023-06-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0007_participationtypemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationmodel',
            name='intensity',
        ),
        migrations.AddField(
            model_name='participationmodel',
            name='points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
