# Generated by Django 4.2 on 2023-06-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0008_remove_participationmodel_intensity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unapprovedparticipation',
            options={'verbose_name': 'Participation not approved', 'verbose_name_plural': 'Participations not approved'},
        ),
    ]
