# Generated by Django 4.2 on 2023-06-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0011_participationmodel_is_to_considered_for_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationmodel',
            name='date_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
