# Generated by Django 4.2 on 2023-06-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0012_alter_participationmodel_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationmodel',
            name='name',
        ),
    ]
