# Generated by Django 4.2 on 2023-06-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0013_remove_participationmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unapprovedparticipation',
            options={'verbose_name': 'Participation to approve', 'verbose_name_plural': 'Participations to approve'},
        ),
    ]
# Generated by Django 4.2 on 2023-06-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0013_remove_participationmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unapprovedparticipation',
            options={'verbose_name': 'Participation to approve', 'verbose_name_plural': 'Participations to approve'},
        ),
    ]
