# Generated by Django 4.2 on 2023-06-29 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0003_contestsmodel_nb_element_leaderboard'),
        ('participation', '0013_remove_participationmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unapprovedparticipation',
            options={'verbose_name': 'Participation to approve', 'verbose_name_plural': 'Participations to approve'},
        ),
        migrations.CreateModel(
            name='DrawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField()),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestsmodel')),
                ('draw_100_for_28_days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_100_for_28_days', to=settings.AUTH_USER_MODEL)),
                ('draw_150_for_35_days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_150_for_35_days', to=settings.AUTH_USER_MODEL)),
                ('draw_50_for_21_days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_50_for_21_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Draw',
                'verbose_name_plural': 'Draw',
            },
        ),
    ]
