# Generated by Django 4.2 on 2023-07-03 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participation', '0014_alter_unapprovedparticipation_options_drawmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(default=1, max_length=200)),
                ('participation_day', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='drawmodel',
            name='draw_100_for_28_days',
        ),
        migrations.RemoveField(
            model_name='drawmodel',
            name='draw_150_for_35_days',
        ),
        migrations.RemoveField(
            model_name='drawmodel',
            name='draw_50_for_21_days',
        ),
        migrations.AddField(
            model_name='drawmodel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawmodel',
            name='date_created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='drawmodel',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawmodel',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participation.levelmodel'),
        ),
    ]
