# Generated by Django 4.2 on 2023-07-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0014_alter_unapprovedparticipation_options'),
        ('participation', '0015_levelmodel_remove_drawmodel_draw_100_for_28_days_and_more'),
    ]

    operations = [
    ]
