# Generated by Django 4.2 on 2023-07-05 19:49

import apps.participation.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0016_merge_20230704_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationmodel',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.participation.models.participation_picture_path),
        ),
    ]
