# Generated by Django 4.2 on 2023-08-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0017_alter_participationmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationmodel',
            name='status',
            field=models.CharField(choices=[('ADMIN', 'In verification'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='ADMIN', max_length=50, verbose_name='Status'),
        ),
    ]
