# Generated by Django 4.2 on 2023-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0018_participationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationtypemodel',
            name='can_add_more_by_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participationtypemodel',
            name='can_be_intensive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='status',
            field=models.CharField(choices=[('IN_VERIFICATION', 'In verification'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='IN_VERIFICATION', max_length=50, verbose_name='Status'),
        ),
    ]
