# Generated by Django 4.2 on 2023-08-24 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participation', '0019_participationtypemodel_can_add_more_by_day_and_more'),
    ]

    def initParticipationType(apps, schema_editor):
        type_list = ['Défis Popup', 'Henry et sa Gang']
        ParticipationTypeModel = apps.get_model('participation', 'ParticipationTypeModel')
        ParticipationTypeModel.objects.create(
            name='Normal',
            can_be_intensive=True,
            can_add_more_by_day=True
        )
        for type in type_list:
            ParticipationTypeModel.objects.create(
                name=type
            )
    operations = [
        migrations.AlterModelOptions(
            name='participationtypemodel',
            options={'ordering': ['pk'], 'verbose_name': 'Participation type', 'verbose_name_plural': 'Participations type'},
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participation.participationtypemodel'),
        ),
        migrations.CreateModel(
            name='ReactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=150, verbose_name='Reactions')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participation.participationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'ordering': ['-pk'],
                'unique_together': {('user', 'participation')},
            },
        ),
        migrations.RunPython(initParticipationType),
    ]
