# Generated by Django 4.2 on 2023-08-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0019_participationtypemodel_can_add_more_by_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationtypemodel',
            options={'ordering': ['pk'], 'verbose_name': 'Participation type', 'verbose_name_plural': 'Participations type'},
        ),
    ]
