# Generated by Django 4.2 on 2023-08-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0020_alter_participationtypemodel_options_and_more'),
    ]

    def updateOrganizatorField(apps, schema_editor):
        type_list = ['Défis Popup', 'Henry et sa Gang']
        ParticipationTypeModel = apps.get_model('participation', 'ParticipationTypeModel')
        ParticipationTypeModel.objects.filter(name__in=type_list).update(can_have_organizer=True)

    operations = [
        migrations.AddField(
            model_name='participationmodel',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participationtypemodel',
            name='can_have_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(updateOrganizatorField),
    ]
