# Generated by Django 4.2 on 2023-08-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0021_participationmodel_is_organizer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnApprovedParticipation',
        ),
        migrations.CreateModel(
            name='ApproveParticipation',
            fields=[
            ],
            options={
                'verbose_name': 'Participation to approve',
                'verbose_name_plural': 'Participations to approve',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('participation.participationmodel',),
        ),
        migrations.CreateModel(
            name='RejectParticipation',
            fields=[
            ],
            options={
                'verbose_name': 'Participation to reject',
                'verbose_name_plural': 'Participations to reject',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('participation.participationmodel',),
        ),
        migrations.CreateModel(
            name='UnapproveParticipation',
            fields=[
            ],
            options={
                'verbose_name': 'Participation to unapproved',
                'verbose_name_plural': 'Participations to unapproved',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('participation.participationmodel',),
        ),
        migrations.RemoveField(
            model_name='participationmodel',
            name='is_approved',
        ),
    ]
