# Generated by Django 4.2 on 2023-09-01 16:45

import apps.participation.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('participation', '0022_delete_unapprovedparticipation_approveparticipation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationtypemodel',
            name='can_be_display_on_feed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participationtypemodel',
            name='could_set_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(),
                                    upload_to=apps.participation.models.participation_picture_path),
        ),

    ]
