# Generated by Django 4.2 on 2023-09-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0023_participationtypemodel_can_be_display_on_feed_and_more'),
    ]

    def updatePopUpType(apps, schema_editor):
        type_list = ['Défis Popup']
        ParticipationTypeModel = apps.get_model('participation', 'ParticipationTypeModel')
        ParticipationTypeModel.objects.filter(name__in=type_list).update(should_set_image=False,
                                                                         shoul_be_display_on_feed=False)

    operations = [
        migrations.RenameField(
            model_name='participationtypemodel',
            old_name='can_be_display_on_feed',
            new_name='shoul_be_display_on_feed',
        ),
        migrations.RenameField(
            model_name='participationtypemodel',
            old_name='could_set_image',
            new_name='should_set_image',
        ),
        migrations.RemoveField(
            model_name='participationmodel',
            name='is_to_considered_for_day',
        ),
        migrations.RunPython(updatePopUpType),
    ]
