# Generated by Django 4.2 on 2023-09-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0024_rename_can_be_display_on_feed_participationtypemodel_shoul_be_display_on_feed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawmodel',
            name='total_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
