# Generated by Django 4.2 on 2023-09-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0025_drawmodel_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawmodel',
            name='office',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='levelmodel',
            name='is_for_office',
            field=models.BooleanField(default=False),
        ),
    ]
