# Generated by Django 4.2 on 2023-09-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0026_drawmodel_office_levelmodel_is_for_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
