# Generated by Django 4.2 on 2023-09-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0026_levelmodel_name_en_levelmodel_name_fr_and_more'),
        ('participation', '0027_alter_participationmodel_description'),
    ]

    operations = [
    ]
