# Generated by Django 4.2 on 2023-09-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0028_merge_20230918_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationmodel',
            options={'ordering': ['date'], 'verbose_name': 'Participation', 'verbose_name_plural': 'Participations'},
        ),
    ]
