# Generated by Django 4.2 on 2023-09-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0029_alter_participationmodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApproveParticipation',
        ),
        migrations.DeleteModel(
            name='RejectParticipation',
        ),
        migrations.DeleteModel(
            name='UnapproveParticipation',
        ),
        migrations.CreateModel(
            name='PendingParticipation',
            fields=[
            ],
            options={
                'verbose_name': 'Participation en attente',
                'verbose_name_plural': 'Participations en attente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('participation.participationmodel',),
        ),
        migrations.CreateModel(
            name='ResolvedParticipation',
            fields=[
            ],
            options={
                'verbose_name': 'Participation résolue',
                'verbose_name_plural': 'Participations résolues',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('participation.participationmodel',),
        ),
        migrations.AlterModelOptions(
            name='participationmodel',
            options={'ordering': ['-date_created', '-id'], 'verbose_name': 'Participation', 'verbose_name_plural': 'Participations'},
        ),
    ]
