# Generated by Django 4.2 on 2023-09-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0032_alter_resolvedparticipation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingparticipation',
            options={'verbose_name': 'Participation à revoir', 'verbose_name_plural': 'Participations à revoir'},
        ),
        migrations.AlterModelOptions(
            name='resolvedparticipation',
            options={'verbose_name': 'Participation revue', 'verbose_name_plural': 'Participations revues'},
        ),
    ]
