# Generated by Django 4.2 on 2023-10-04 16:17

import apps.participation.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0007_remove_contestsmodel_nb_element_leaderboard_and_more'),
        ('participation', '0033_alter_pendingparticipation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawmodel',
            options={'ordering': ['contest', 'level'], 'verbose_name': 'Draw', 'verbose_name_plural': 'Draw'},
        ),
        migrations.AlterField(
            model_name='drawmodel',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestsmodel', verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='drawmodel',
            name='date_created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='drawmodel',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='drawmodel',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participation.levelmodel', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='drawmodel',
            name='office',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='drawmodel',
            name='total_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Days completed'),
        ),
        migrations.AlterField(
            model_name='drawmodel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Winner'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='date_created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active ?'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='is_for_office',
            field=models.BooleanField(default=False, verbose_name='For office ?'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='participation_day',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Participation days'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='price',
            field=models.CharField(default=1, max_length=200, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contestsmodel', verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='date_created',
            field=models.DateTimeField(editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.participation.models.participation_picture_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='is_intensive',
            field=models.BooleanField(default=False, verbose_name='High Intensity'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='Initiator'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='last_modified',
            field=models.DateTimeField(verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Pts'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participation.participationtypemodel', verbose_name='Participation type'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='can_add_more_by_day',
            field=models.BooleanField(default=False, verbose_name='Can add more by day ?'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='can_be_intensive',
            field=models.BooleanField(default=False, verbose_name='Can be intensive ?'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='can_have_organizer',
            field=models.BooleanField(default=False, verbose_name='Can have initiator ?'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='From date'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='shoul_be_display_on_feed',
            field=models.BooleanField(default=True, verbose_name='Shoul be display on feed ?'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='should_set_image',
            field=models.BooleanField(default=True, verbose_name='Should set image ?'),
        ),
        migrations.AlterField(
            model_name='participationtypemodel',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='To date'),
        ),
    ]
