# Generated by Django 4.2 on 2023-06-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestsmodel',
            options={'ordering': ['-pk'], 'verbose_name': 'Contest', 'verbose_name_plural': 'Contests'},
        ),
    ]
