# Generated by Django 4.2 on 2023-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contestsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsmodel',
            name='nb_element_leaderboard',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
