# Generated by Django 4.2 on 2023-09-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contestsmodel_nb_element_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsmodel',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contestsmodel',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
