# Generated by Django 4.2.5 on 2023-09-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0005_contestsmodel_show_winners_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contestsmodel",
            name="Only one contest can be set to True at a time",
        ),
        migrations.AddConstraint(
            model_name="contestsmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_open", True)),
                fields=("is_open",),
                name="unique_is_open_true",
            ),
        ),
    ]
