# Generated by Django 4.2 on 2023-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_remove_contestsmodel_only_one_contest_can_be_set_to_true_at_a_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestsmodel',
            name='nb_element_leaderboard',
        ),
        migrations.AlterField(
            model_name='contestsmodel',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='contestsmodel',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='contestsmodel',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Open ?'),
        ),
        migrations.AlterField(
            model_name='contestsmodel',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='contestsmodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Contest name'),
        ),
        migrations.AlterField(
            model_name='contestsmodel',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Contest name'),
        ),
        migrations.AlterField(
            model_name='contestsmodel',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Contest name'),
        ),
        migrations.AlterField(
            model_name='contestsmodel',
            name='show_winners',
            field=models.BooleanField(default=False, verbose_name='Show winners'),
        ),
        migrations.AlterField(
            model_name='contestsmodel',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
